### ISSUE TITLE
Randomize

### ISSUE THREAD

**Issue by Trebors2** [platform-coop-toolkit/pcc#134]
**Describe the bug**

The Randomize feature of the Participant page has been disabled. Please switch it on again.

**To Reproduce**

**Expected behavior**

Profiles on the Participant page should appear in random order when one reloads the page. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by greatislander** [comment]
@Trebors2 I removed this for two reasons:

1. The website uses page caching, which means that the page will always display in the same "random" order to logged-out visitors unless new people are added.
2. If I disable caching on the page so that visitors see a different order each time they visit the participants page, it becomes incredibly frustrating to navigate as there's no predictable way to find the same person upon repeated vists to the page.

I'm going add a field to allow you to highlight six participants at the top of the list (and on the main conference page) and show the remaining participants alphabetically.
